### ISSUE TITLE
better background fill behavior

### ISSUE THREAD

**Issue by TadLeonard** [TadLeonard/crash_kiss#9]
When we shift the subject over we naively fill the vacated space with white [255, 255, 255]. We should do something smarter like sampling the background or giving the user a `--bg-fill-value` option. See left and right edges of the attached image to observe the obviously-white fill value clashing against the obviously-not-white background.

![out2](https://cloud.githubusercontent.com/assets/6044830/6065618/6dd9559e-ad2c-11e4-91f0-e9d14f7f1715.jpg)

**Comment by TadLeonard** [comment]
@rollinleonard reports that this issue should be closed as a wontfix because it's against the spirit of the program to add data to the image that isn't just "blank".

**Comment by rollinleonard** [comment]
I fucking love how this works.

On Mon, Feb 9, 2015 at 2:10 PM, TadLeonard <notifications@github.com> wrote:

> Closed #9 <https://github.com/TadLeonard/crash_kiss/issues/9>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TadLeonard/crash_kiss/issues/9#event-232693222>.
>



-- 

Rollin Leonard
+12073327293
rollinleonard.com
